TypeError: Cannot read properties of undefined (reading 'setSelectedCohorts') - undefined not showing up as type option at all - pivoting to [] - may still need to update the selectedCohorts function